import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

import 'firebase_options.dart'; // generated by `flutterfire configure` (you already have it)
import 'models/user_profile.dart';
import 'screens/dashboard_screen.dart';
import 'screens/login_screen.dart'; // YOUR existing login screen (class LoginScreen)
import 'screens/profile_screen.dart';
import 'services/firestore_service.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Required for Firebase AI Logic (enforced from 2 Nov 2026).
  // Debug provider on emulator: copy the debug token printed in the console
  // into Firebase console → App Check → Apps → Manage debug tokens.
  await FirebaseAppCheck.instance.activate(
    androidProvider: kDebugMode ? AndroidProvider.debug : AndroidProvider.playIntegrity,
    appleProvider: kDebugMode ? AppleProvider.debug : AppleProvider.appAttest,
  );

  runApp(const EarlyWarningApp());
}

class EarlyWarningApp extends StatelessWidget {
  const EarlyWarningApp({super.key});

  @override
  Widget build(BuildContext context) => MaterialApp(
        title: 'Early Warning',
        theme: ThemeData(colorSchemeSeed: Colors.deepPurple, useMaterial3: true),
        home: const AuthGate(),
      );
}

/// Not signed in → LoginScreen; profile incomplete → ProfileScreen;
/// otherwise → DashboardScreen.
class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) => StreamBuilder<User?>(
        stream: FirebaseAuth.instance.authStateChanges(),
        builder: (context, auth) {
          if (auth.connectionState == ConnectionState.waiting) {
            return const Scaffold(body: Center(child: CircularProgressIndicator()));
          }
          final user = auth.data;
          if (user == null) return const LoginScreen();
          return StreamBuilder<UserProfile?>(
            stream: FirestoreService.instance.profileStream(user.uid),
            builder: (context, ps) {
              if (!ps.hasData && ps.connectionState == ConnectionState.waiting) {
                return const Scaffold(body: Center(child: CircularProgressIndicator()));
              }
              final p = ps.data;
              if (p == null || !p.profileCompleted) return ProfileScreen(existing: p);
              return const DashboardScreen();
            },
          );
        },
      );
}
